### ISSUE TITLE
Install fails : nvcc fatal   : redefinition of argument 'std'

### ISSUE THREAD

**Issue by htoyryla** [gchanan/TemporalConvolutionTBC#2] opened 2017-05-10 07:42 UTC
Any idea what goes wrong here? 

On the line just before the error message nvcc actually gets -std twice.

Ubuntu 14.04. Cmake version is 2.8.12.2.
```
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/hannu/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/hannu/torch/install/lib/luarocks/rocks/tbc/scm-1" && make
   
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/hannu/torch/install
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- CUDA Found
-- Autodetected CUDA architecture(s): 6.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hannu/temp/TemporalConvolutionTBC/build
[ 50%] Building NVCC (Device) object lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
-- Removing /home/hannu/temp/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
/usr/bin/cmake -E remove /home/hannu/temp/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
-- Generating dependency file: /home/hannu/temp/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//THTBC_generated_init_cuda.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/hannu/temp/TemporalConvolutionTBC/lib/init_cuda.cu -o /home/hannu/temp/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//THTBC_generated_init_cuda.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 --std c++11 -DTORCH_TBC_CUDA -DTHTBC_EXPORTS -Xcompiler ,\"-fPIC\",\"-O3\",\"-DNDEBUG\" -std c++11 -DNVCC -I/home/hannu/temp/TemporalConvolutionTBC/lib -I/usr/local/cuda-8.0/include -I/home/hannu/torch/install/include -I/home/hannu/torch/install/include/TH -I/usr/local/cuda-8.0/include -I/home/hannu/torch/install/include/THC
nvcc fatal   : redefinition of argument 'std'
CMake Error at THTBC_generated_init_cuda.cu.o.cmake:207 (message):
  Error generating
  /home/hannu/temp/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o


make[2]: *** [lib/CMakeFiles/THTBC.dir/./THTBC_generated_init_cuda.cu.o] Error 1
make[1]: *** [lib/CMakeFiles/THTBC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
``

**Comment by htoyryla** [comment] 2017-05-10 17:31
In my case I managed to compile and install by removing OPTIONS -std c++11
on this line https://github.com/gchanan/TemporalConvolutionTBC/blob/master/lib/CMakeLists.txt#L43

**Comment by htoyryla** [comment] 2017-05-10 17:37
Might be something wrong still, as test with CudaTensor fails:
```
nn.TemporalConvolutionTBC.test().checkforwardbackward(nil, nil, nil, nil, nil, nil, 'torch.CudaTensor')
delta	6.7445010186304e-07
...rch/install/share/lua/5.1/tbc/TemporalConvolutionTBC.lua:123: 6.7445010186304e-07
stack traceback:
	[C]: in function 'assert'
	...rch/install/share/lua/5.1/tbc/TemporalConvolutionTBC.lua:123: in function 'checkforwardbackward'
	[string "_RESULT={nn.TemporalConvolutionTBC.test().che..."]:1: in main chunk
	[C]: in function 'xpcall'
	/home/hannu/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...annu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x004065d0
```

**Comment by SuperWu090** [comment] 2017-05-12 03:08
@htoyryla I have the same problem when installing the fairseq. Have you solved the it yet?

**Comment by gchanan** [comment] 2017-05-12 03:17
does the test fail for you without cuda?  i.e. using 'torch.FloatTensor'?

**Comment by SuperWu090** [comment] 2017-05-12 03:32
@gchanan It is OK without CUDA. I don't how to make it run properly with CUDA.

**Comment by gchanan** [comment] 2017-05-12 03:47
and you are on OS X?

**Comment by SuperWu090** [comment] 2017-05-12 03:53
@gchanan I am on Ubuntu 14.04, CMake 2.8.12, just as @htoyryla. I also removed the 'OPTIONS -std c++11'.

**Comment by htoyryla** [comment] 2017-05-12 05:12
Test ok here with FloatTensor, also with CudaDoubleTensor and CudaHalfTensor. Only CudaTensor fails in the assert after printing out the first delta. 

Despite this, fairseq works here (at least generate_lines; haven't tried trainining though).

**Comment by yongjincho** [comment] 2017-05-12 05:13
I'm using centos 7 and cmake version is 2.8.12.2.  I had the same issue.

After installing the latest version of cmake (3.8.1), the problem is solved.  If you still have this problem, try upgrading your cmake.

**Comment by htoyryla** [comment] 2017-05-12 05:32
Interests me though why this test error with CudaTensor happens.

**Comment by htoyryla** [comment] 2017-05-12 06:00
I have cmake 3.8.1 now, and after installing tbc from a clean copy the CudaTensor test still gives the same error. @yongjincho does CudaTensor test work ok for you? 

@gchanan, I looked into what the assert does. For me, both CudaTensor and FloatTensor give deltas around 5e-7, while the assert expects much better accuracy. DoubleTensor and CudaDoubleTensor give deltas around e-15 or e-16. Makes me wonder if the test condition is correct?

**Comment by gchanan** [comment] 2017-05-12 15:36
@htoyryla I believe you are correct about the test precision being wrong.

**Comment by gchanan** [comment] 2017-05-12 15:42
Test precision issue should be fixed by https://github.com/gchanan/TemporalConvolutionTBC/pull/3.

**Comment by gchanan** [comment] 2017-05-12 17:21
I was able to reproduce the build issue by downgrading cmake to 2.8.  https://github.com/gchanan/TemporalConvolutionTBC/pull/4 should fix the issue.

**Comment by gchanan** [comment] 2017-05-12 17:21
Thanks for helping me track these down!

**Closed as completed by gchanan** 2017-05-12 17:21 UTC

**Comment by Jon-drugstore** [comment] 2020-10-26 11:37
> In my case I managed to compile and install by removing OPTIONS -std c++11
> on this line https://github.com/gchanan/TemporalConvolutionTBC/blob/master/lib/CMakeLists.txt#L43
remove the option '-std=c++11' from:
`list(APPEND CUDA_NVCC_FLAGS -std=c++11)
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -std=c++11")` 
to 
`list(APPEND CUDA_NVCC_FLAGS)
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS}")`
